# Generated by Django 5.1.4 on 2024-12-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
